<?php

// THIS IS THE ABSOLUTE LOCATION OF NMAP
$NMAP = '/usr/bin/nmap';

// THIS IS THE ABSOLUTE LOCATION OF SUDO
$SUDO = '/usr/bin/sudo';

// ALLOW SCANNING OF MULTIPLE HOSTS
// This will allow users to scan whole ranges of ips
$MULTIPLE_HOSTS = YES;

// DEBUG MODE
// This may reveal more information than desired such as 
// errors generated by sudo or nmap
$DEBUG = YES;

// SOURCE ADDRESS
// In some circumstances, nmap may not be ablt to determine your
// source address (nmap will tell you if this is the case).
$SOURCE_ADDRESS ='';

// INTERFACE
// Tells nmap what interface to send and receive packets on
// NMAP will auto detect interface, it will tell you if it cannot
$INTERFACE ='';

// SOURCE PORT
// Set the source port number used in scans. This may help to get
// by some firewalls/packet filters
$SOURCE_PORT='';

?>
